title: Kaneesha Dawood # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! I am Kaneesha Dawood, a data scientist with expertise in database systems and statistical analysis. I develop analytical solutions to help solve real-life problems. 
  <br><br>
  I am an avid learner, adventurer, and data enthusiast. I am passionate about making an impact, finding data-driven solutions, and helping communities achieve their data-centric goals. 
  <br><br>
  <a href="https://www.linkedin.com/in/kaneeshadawood/">LinkedIn</a> 
  
theme: jekyll-theme-hacker
google_analytics: 172024996 # your Google Analytics tracking ID here
